#!/bin/bash

BASEDIR=$(cd "$(dirname "$0")"; pwd)

INPUT=$1   # .sas file
OUTPUT=$2  # .plan file

PREPROCESS="$BASEDIR/preprocess"
PLANNER="$BASEDIR/downward"
ENGINE="lmcut"

#REMOVED_OPERATOR="\(verifyGlobal\)"
REMOVED_OPERATOR="-goal_"
TEMP_DIR="/tmp/sfp_$RANDOM"
CURRENT_DIR=`PWD`

# generate absolute path for the input file
if [ ${INPUT:0:1} != "/" ]; then
	INPUT="$CURRENT_DIR/$INPUT"
fi

# generate working directory
mkdir $TEMP_DIR
cd $TEMP_DIR

# run preprocess
$PREPROCESS < $INPUT #&> /dev/null

if [ -e $TEMP_DIR/output ]; then
	# search the plan
	if [[ "$ENGINE" == "ff" ]]; then
		$PLANNER \
			--heuristic "hff=ff()" \
			--search "lazy_greedy(hff, preferred=hff)" < $TEMP_DIR/output &> /dev/null
	elif [[ "$ENGINE" == "lama2011" ]]; then
		$PLANNER \
			--heuristic "hlm,hff=lm_ff_syn(lm_rhw(
				reasonable_orders=true,lm_cost_type=2,cost_type=2))" \
			--search "iterated([
				lazy_greedy([hff,hlm],preferred=[hff,hlm]),
				lazy_wastar([hff,hlm],preferred=[hff,hlm],w=5),
				lazy_wastar([hff,hlm],preferred=[hff,hlm],w=3),
				lazy_wastar([hff,hlm],preferred=[hff,hlm],w=2),
				lazy_wastar([hff,hlm],preferred=[hff,hlm],w=1)],
				repeat_last=true,continue_on_fail=true)" \
			< $TEMP_DIR/output &> /dev/null
	elif [[ "$ENGINE" == "lmcut" ]]; then
		$PLANNER --search "astar(lmcut())" < $TEMP_DIR/output &> /dev/null
	elif [[ "$ENGINE" == "blind" ]]; then
		$PLANNER --search "astar(blind())" < $TEMP_DIR/output &> /dev/null
	fi
fi

cd $CURRENT_DIR

# remove unused operator and generate the final output
if [ -e $TEMP_DIR/sas_plan ]; then
	SED_ARGS="/$REMOVED_OPERATOR/d"
	sed $SED_ARGS $TEMP_DIR/sas_plan 1> $OUTPUT
fi

# remove unused file
rm -f plan_numbers_and_cost
rm -rf $TEMP_DIR
