#!/bin/bash

HOME=$(dirname $(readlink -f $0))

INPUT=$1   # .sas file
OUTPUT=$2  # .plan file

PREPROCESS="$HOME/preprocess" 
PLANNER="$HOME/downward"

if [[ "$ENGINE" == "" ]]; then
	ENGINE="lmcut"
fi

#REMOVED_OPERATOR="\(verifyGlobal\)"
REMOVED_OPERATOR="\(-goal_\)"
TEMP_DIR="/tmp/sfp_$RANDOM"
CURRENT_DIR=`pwd`

# generate absolute path for the input file
if [ ${INPUT:0:1} != "/" ]; then
	INPUT="$CURRENT_DIR/$INPUT"
fi

# create working directory
mkdir $TEMP_DIR
cd $TEMP_DIR

# run preprocess
$PREPROCESS < $INPUT > output

# search the plan
if [[ "$ENGINE" == "ff" ]]; then
	$PLANNER \
		--heuristic "hff=ff()" \
		--search "lazy_greedy(hff, preferred=hff)" < $TEMP_DIR/output &> /dev/null
elif [[ "$ENGINE" == "lama2011" ]]; then
	$PLANNER \
		--heuristic "hlm,hff=lm_ff_syn(lm_rhw(
			reasonable_orders=true,lm_cost_type=2,cost_type=2))" \
		--search "iterated([
			lazy_greedy([hff,hlm],preferred=[hff,hlm]),
			lazy_wastar([hff,hlm],preferred=[hff,hlm],w=5),
			lazy_wastar([hff,hlm],preferred=[hff,hlm],w=3),
			lazy_wastar([hff,hlm],preferred=[hff,hlm],w=2),
			lazy_wastar([hff,hlm],preferred=[hff,hlm],w=1)],
			repeat_last=true,continue_on_fail=true)" \
		< $TEMP_DIR/output &> /dev/null
elif [[ "$ENGINE" == "lmcut" ]]; then
	$PLANNER --search "astar(lmcut())" < $TEMP_DIR/output &> /dev/null
elif [[ "$ENGINE" == "blind" ]]; then
	$PLANNER --search "astar(blind())" < $TEMP_DIR/output &> /dev/null
fi

cd $CURRENT_DIR

# remove unused operator
if [ -e $TEMP_DIR/sas_plan ]; then
	SED_ARGS="/$REMOVED_OPERATOR/d"
	sed $SED_ARGS $TEMP_DIR/sas_plan 1> $OUTPUT
fi

# remove temporary files
rm -rf $TEMP_DIR
