#!/bin/bash

HOME=$(dirname $(readlink -f $0))

INPUT=$1   # .sas file
OUTPUT=$2  # .plan file

PREPROCESS="$HOME/preprocess" 
PLANNER="$HOME/downward" 

REMOVED_OPERATOR="\(verifyGlobal\)"
TEMP_DIR="/tmp/sfp_$RANDOM"
CURRENT_DIR=`pwd`

# generate absolute path for the input file
if [ ${INPUT:0:1} != "/" ]; then
	INPUT="$CURRENT_DIR/$INPUT"
fi

# create working directory
mkdir $TEMP_DIR
cd $TEMP_DIR

# run preprocess
$PREPROCESS < $INPUT > output

# search the plan
$PLANNER --heuristic "hff=ff()" --search "lazy_greedy(hff, preferred=hff)" < $TEMP_DIR/output &> /dev/null

cd $CURRENT_DIR

# remove unused operator
SED_ARGS="/$REMOVED_OPERATOR/d"
/bin/sed $SED_ARGS $TEMP_DIR/sas_plan > $OUTPUT

# remove temporary files
rm -rf $TEMP_DIR
