#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import json
import os
import io
import commands
import platform

###############
#
# Method for generating current state
#
###############
def get_state(model):
	state = {}
	state['memory_total'] = 0
	state['memory_free'] = 0
	state['node'] = platform.node()
	state['system'] = platform.system()
	state['release'] = platform.release()
	state['arch'] = platform.machine()
	state['processor'] = platform.processor()
	state['platform'] = platform.platform()
	state['python'] = platform.python_version()
	#state['dist'] = platform.linux_distribution()
	### dump current state
	print json.dumps({'status': 'ok', 'state': state})


###############
#
# Function to redirect procedure execution request by
# calling target function
#
###############
def execute(procedure, parameters, model):
	status = 'failed'
	description = 'invalid action'
	print json.dumps({'status': status, 'description': description})


###############
#
# Main logic for handling any request
#
###############
if len(sys.argv) <= 1:
	### invalid request
	print '{"status":"error","description":"invalid command line argument"}'
	exit(1)
else:
	### parse request data in JSON
	data = json.loads(sys.argv[1])

	if 'request' in data:
		try:
			if data['request'] == 'state' and 'model' in data:
				### request for current state
				get_state(data['model'])

			elif data['request'] == 'execute' and 'action' in data and 'parameters' in data and 'model' in data:
				### request for executing a procedure
				execute(data['action'], data['parameters'], data['model'])

			else:
				### invalid request
				print '{"status":"error","description":"invalid command"}'
				exit(1)

		except Exception, e:
			### dump exception
			print json.dumps({'status':'error','description': str(e)})

	else:
		### invalid request
		print '{"status":"error","description":"no command"}'
		exit(1)

exit(0)
